import type { QuestionSeed } from '../types';

// Preguntas específicas para el régimen futuro (Ley N.º 21.719). Solo se
// activan cuando el diagnóstico se ejecuta en modo FUTURO o TRANSICION.
export const FUTURO_QUESTIONS: QuestionSeed[] = [
  {
    code: 'Q-FUT-001',
    category: 'Régimen futuro (Ley 21.719)',
    text: '¿La organización tiene designado o planea designar un responsable interno para las relaciones con la futura Agencia de Protección de Datos Personales?',
    answerType: 'YES_NO_UNKNOWN',
    required: false,
    order: 200,
    justification: 'El nuevo marco crea una autoridad especializada de fiscalización.',
    legalMatter: 'Institucionalidad y fiscalización',
    norm: 'Ley N.º 21.719',
    source: 'L21719-001',
    riskLevel: 'medio',
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-FUT-002',
    category: 'Régimen futuro (Ley 21.719)',
    text: 'Para cada tratamiento identificado, ¿podría indicar cuál sería su base de licitud bajo el nuevo régimen (consentimiento, ejecución de contrato, obligación legal, interés legítimo, etc.)?',
    answerType: 'TABLE',
    required: false,
    order: 210,
    justification: 'El nuevo régimen exige base de licitud específica por tratamiento.',
    legalMatter: 'Licitud del tratamiento',
    norm: 'Ley N.º 21.719',
    source: 'L21719-002',
    riskLevel: 'alto',
    visibilityCondition: { op: 'nonEmpty', path: 'processingActivities' },
  },
  {
    code: 'Q-FUT-003',
    category: 'Régimen futuro (Ley 21.719)',
    text: '¿La organización estaría en condiciones de responder solicitudes de portabilidad de datos si el nuevo régimen las exige?',
    answerType: 'YES_NO_UNKNOWN',
    required: false,
    order: 220,
    justification: 'El nuevo marco ampliaría los derechos de los titulares.',
    legalMatter: 'Derechos de los titulares',
    norm: 'Ley N.º 21.719',
    source: 'L21719-003',
    riskLevel: 'medio',
    visibilityCondition: { op: 'nonEmpty', path: 'dataSubjects' },
  },
  {
    code: 'Q-FUT-004',
    category: 'Régimen futuro (Ley 21.719)',
    text: 'Describa el tratamiento de alto riesgo identificado (datos sensibles a gran escala, perfilamiento, IA, videovigilancia) con el mayor detalle posible.',
    answerType: 'LONG_TEXT',
    required: false,
    order: 230,
    justification: 'Permite evaluar si correspondería una evaluación de impacto bajo el nuevo régimen.',
    legalMatter: 'Tratamientos de alto riesgo',
    norm: 'Ley N.º 21.719',
    source: 'L21719-004',
    riskLevel: 'alto',
    requiresDocument: true,
    visibilityCondition: {
      any: [
        { op: 'nonEmpty', path: 'sensitiveData' },
        { op: 'includesAny', path: 'technologies', values: ['inteligencia artificial', 'perfilamiento', 'scoring', 'videovigilancia'] },
      ],
    },
  },
  {
    code: 'Q-FUT-005',
    category: 'Régimen futuro (Ley 21.719)',
    text: 'Dado el volumen de titulares o el tratamiento de datos sensibles identificado, ¿la organización cuenta con una persona o equipo a cargo de la protección de datos?',
    answerType: 'YES_NO_UNKNOWN',
    required: false,
    order: 240,
    justification: 'Podría corresponder designar un Delegado de Protección de Datos bajo el nuevo régimen.',
    legalMatter: 'Gobernanza de datos',
    norm: 'Ley N.º 21.719',
    source: 'L21719-005',
    riskLevel: 'medio',
    visibilityCondition: {
      any: [
        { op: 'gte', path: 'organization.estimatedDataSubjects', value: 10000 },
        { op: 'nonEmpty', path: 'sensitiveData' },
      ],
    },
  },
  {
    code: 'Q-FUT-006',
    category: 'Régimen futuro (Ley 21.719)',
    text: 'Para cada transferencia internacional identificada, ¿qué mecanismo de resguardo utiliza o utilizaría (cláusulas contractuales, evaluación de adecuación del país, consentimiento del titular)?',
    answerType: 'TABLE',
    required: false,
    order: 250,
    justification: 'El nuevo régimen regularía con mayor especificidad las transferencias internacionales.',
    legalMatter: 'Transferencias internacionales',
    norm: 'Ley N.º 21.719',
    source: 'L21719-006',
    riskLevel: 'alto',
    visibilityCondition: { op: 'nonEmpty', path: 'internationalTransfers' },
  },
];
