import type { QuestionSeed } from '../types';

export const GENERAL_QUESTIONS: QuestionSeed[] = [
  {
    code: 'Q-GEN-001',
    category: 'Organización',
    text: '¿Cuál es la actividad económica principal de la organización y sus líneas de negocio secundarias?',
    answerType: 'LONG_TEXT',
    required: true,
    order: 10,
    justification: 'Determina el marco regulatorio general aplicable y los sectores potencialmente activados.',
    legalMatter: 'Ámbito de aplicación general',
    norm: 'Ley N.º 19.628',
    source: 'L19628-001',
    riskLevel: 'bajo',
    lawyerExplanation: 'Define el punto de partida del diagnóstico: sin actividad clara no es posible acotar sectores ni tratamientos.',
    clientExplanation: 'Cuéntenos a qué se dedica su organización, en sus palabras.',
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-GEN-002',
    category: 'Organización',
    text: '¿Cuántos trabajadores tiene la organización y cuántos titulares de datos (clientes, usuarios, pacientes, alumnos, etc.) estima que gestiona?',
    answerType: 'SHORT_TEXT',
    required: true,
    order: 20,
    justification: 'El volumen de titulares es relevante para evaluar riesgo y eventuales obligaciones de gobernanza (p. ej. DPO) bajo el régimen futuro.',
    legalMatter: 'Dimensionamiento de riesgo',
    riskLevel: 'bajo',
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-TRAT-001',
    category: 'Tratamientos de datos',
    text: 'Describa las principales actividades en las que se recopilan o utilizan datos personales (ventas, atención de clientes, RR.HH., marketing, etc.).',
    answerType: 'TABLE',
    required: true,
    order: 30,
    justification: 'Permite construir el mapa de tratamientos, base de todo el diagnóstico.',
    legalMatter: 'Mapa de tratamientos',
    riskLevel: 'medio',
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-SUBJ-001',
    category: 'Titulares de datos',
    text: '¿Qué categorías de personas (titulares) están involucradas en los tratamientos identificados? (clientes, trabajadores, pacientes, alumnos, proveedores, visitas, etc.)',
    answerType: 'MULTIPLE_CHOICE',
    required: true,
    order: 40,
    options: ['Clientes', 'Trabajadores', 'Pacientes', 'Alumnos/Apoderados', 'Proveedores', 'Visitas', 'Postulantes', 'Otro'],
    justification: 'Base para evaluar derechos ARCO y obligaciones diferenciadas por tipo de titular.',
    legalMatter: 'Derechos de los titulares',
    norm: 'Ley N.º 19.628',
    source: 'L19628-003',
    riskLevel: 'medio',
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-ARCO-001',
    category: 'Derechos de los titulares',
    text: '¿La organización cuenta con un canal o procedimiento para recibir y responder solicitudes de acceso, rectificación, cancelación u oposición de los titulares?',
    answerType: 'YES_NO_UNKNOWN',
    required: true,
    order: 50,
    justification: 'El régimen vigente reconoce derechos del titular; se requiere verificar si existe un procedimiento operativo.',
    legalMatter: 'Derechos de los titulares (habeas data)',
    norm: 'Ley N.º 19.628',
    article: 'REQUIERE VALIDACIÓN JURÍDICA',
    source: 'L19628-003',
    riskLevel: 'medio',
    requiresDocument: true,
    visibilityCondition: { op: 'nonEmpty', path: 'dataSubjects' },
  },
  {
    code: 'Q-DATA-001',
    category: 'Categorías de datos',
    text: '¿Qué categorías de datos personales recopila habitualmente? (identificación, contacto, financieros, laborales, académicos, de salud, biométricos, geolocalización, etc.)',
    answerType: 'MULTIPLE_CHOICE',
    required: true,
    order: 60,
    options: ['Identificación', 'Contacto', 'Financieros', 'Laborales', 'Académicos', 'Salud', 'Biométricos', 'Geolocalización', 'Otro'],
    justification: 'Permite construir el mapa de categorías de datos y detectar posibles datos sensibles.',
    legalMatter: 'Categorías de datos',
    riskLevel: 'medio',
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-SENS-001',
    category: 'Datos sensibles',
    text: 'Para cada dato sensible identificado (salud, afiliación sindical, situación socioeconómica vulnerable, etc.), indique el origen, la finalidad y la base que justificaría su tratamiento.',
    answerType: 'TABLE',
    required: true,
    order: 70,
    justification: 'El tratamiento de datos sensibles exige un régimen reforzado bajo la normativa vigente y futura.',
    legalMatter: 'Datos sensibles',
    norm: 'Ley N.º 19.628',
    source: 'L19628-002',
    riskLevel: 'alto',
    requiresDocument: true,
    visibilityCondition: { op: 'nonEmpty', path: 'sensitiveData' },
  },
  {
    code: 'Q-SENS-002',
    category: 'Datos sensibles',
    text: '¿Existen medidas de seguridad específicas (cifrado, control de acceso restringido, registro de accesos) para los datos sensibles identificados?',
    answerType: 'YES_NO_UNKNOWN',
    required: true,
    order: 80,
    justification: 'Verifica proporcionalidad de las medidas de seguridad frente al riesgo de los datos sensibles.',
    legalMatter: 'Seguridad de datos sensibles',
    riskLevel: 'alto',
    visibilityCondition: { op: 'nonEmpty', path: 'sensitiveData' },
  },
  {
    code: 'Q-PROV-001',
    category: 'Proveedores y terceros',
    text: 'Liste los proveedores o terceros que reciben o acceden a datos personales por encargo de la organización, indicando el servicio que prestan.',
    answerType: 'TABLE',
    required: true,
    order: 90,
    justification: 'Permite construir el mapa de proveedores/terceros y revisar la existencia de cláusulas contractuales adecuadas.',
    legalMatter: 'Encargo de tratamiento a terceros',
    norm: 'Ley N.º 19.628',
    source: 'L19628-004',
    riskLevel: 'medio',
    requiresDocument: true,
    visibilityCondition: { any: [{ op: 'nonEmpty', path: 'providers' }, { op: 'nonEmpty', path: 'thirdParties' }] },
  },
  {
    code: 'Q-PROV-002',
    category: 'Proveedores y terceros',
    text: 'Para cada proveedor listado, ¿existe un contrato vigente que incluya obligaciones de protección de datos personales?',
    answerType: 'YES_NO_UNKNOWN',
    required: false,
    order: 100,
    justification: 'Detecta vacíos contractuales que constituyen riesgo de cumplimiento.',
    legalMatter: 'Encargo de tratamiento a terceros',
    riskLevel: 'medio',
    requiresDocument: true,
    visibilityCondition: { any: [{ op: 'nonEmpty', path: 'providers' }, { op: 'nonEmpty', path: 'thirdParties' }] },
  },
  {
    code: 'Q-TRANSF-001',
    category: 'Transferencias internacionales',
    text: 'Para cada transferencia internacional identificada (por ejemplo, proveedores cloud fuera de Chile), indique el país de destino, el proveedor y la finalidad.',
    answerType: 'TABLE',
    required: true,
    order: 110,
    justification: 'El régimen vigente no regula en detalle las transferencias internacionales; se requiere documentar cada caso para su revisión jurídica específica.',
    legalMatter: 'Transferencias internacionales',
    norm: 'Ley N.º 19.628',
    source: 'L19628-005',
    riskLevel: 'alto',
    requiresDocument: true,
    visibilityCondition: { op: 'nonEmpty', path: 'internationalTransfers' },
  },
  {
    code: 'Q-TEC-001',
    category: 'Tecnologías',
    text: '¿Qué tecnologías o sistemas utiliza para almacenar o procesar datos personales? (ERP, CRM, plataformas cloud, hojas de cálculo, sistemas propios, etc.)',
    answerType: 'MULTIPLE_CHOICE',
    required: true,
    order: 120,
    options: ['CRM', 'ERP', 'Plataforma cloud', 'Hojas de cálculo', 'Sistema propio', 'Otro'],
    justification: 'Permite identificar riesgos técnicos y proveedores tecnológicos asociados.',
    legalMatter: 'Tecnologías y seguridad',
    riskLevel: 'medio',
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-SEG-001',
    category: 'Seguridad de la información',
    text: '¿Qué medidas de seguridad técnicas y organizativas tiene implementadas? (control de acceso, respaldo, cifrado, políticas internas, capacitación)',
    answerType: 'MULTIPLE_CHOICE',
    required: true,
    order: 130,
    options: ['Control de acceso', 'Respaldo (backup)', 'Cifrado', 'Políticas internas', 'Capacitación', 'Ninguna'],
    justification: 'Evalúa la proporcionalidad de las medidas de seguridad frente al riesgo de los tratamientos identificados.',
    legalMatter: 'Seguridad de datos personales',
    riskLevel: 'medio',
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-CONS-001',
    category: 'Conservación y eliminación',
    text: '¿Por cuánto tiempo conserva los datos personales de cada categoría de titular y qué criterio utiliza para definir ese plazo?',
    answerType: 'LONG_TEXT',
    required: true,
    order: 140,
    justification: 'La conservación indefinida o sin criterio es un riesgo recurrente detectado en diagnósticos de protección de datos.',
    legalMatter: 'Conservación y eliminación de datos',
    riskLevel: 'medio',
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-INC-001',
    category: 'Incidentes de seguridad',
    text: 'Describa cualquier incidente de seguridad relevante ocurrido en los últimos 24 meses que haya afectado datos personales (acceso no autorizado, pérdida, filtración, etc.).',
    answerType: 'LONG_TEXT',
    required: false,
    order: 150,
    justification: 'Los incidentes detectados activan obligaciones de notificación bajo el régimen futuro y son relevantes para el marco de ciberseguridad.',
    legalMatter: 'Incidentes de seguridad',
    norm: 'Ley N.º 21.719',
    source: 'L21719-008',
    riskLevel: 'critico',
    requiresDocument: true,
    visibilityCondition: { op: 'nonEmpty', path: 'incidents' },
  },
  {
    code: 'Q-CIBER-001',
    category: 'Ciberseguridad',
    text: '¿La organización cuenta con medidas mínimas de ciberseguridad (control de acceso, respaldo, actualización de sistemas, plan ante incidentes) proporcionales a su infraestructura tecnológica?',
    answerType: 'YES_NO_UNKNOWN',
    required: false,
    order: 155,
    justification: 'Permite evaluar la exposición de la organización frente al marco de ciberseguridad (Ley 21.663) cuando se identifican tecnologías o incidentes relevantes.',
    legalMatter: 'Ciberseguridad',
    norm: 'Ley N.º 21.663',
    source: 'L21663-001',
    riskLevel: 'medio',
    visibilityCondition: { any: [{ op: 'nonEmpty', path: 'technologies' }, { op: 'nonEmpty', path: 'incidents' }] },
  },
  {
    code: 'Q-INC-002',
    category: 'Incidentes de seguridad',
    text: 'En caso de un incidente, ¿se evaluó la posibilidad de que constituyera un delito informático y se evaluó realizar una denuncia?',
    answerType: 'YES_NO_UNKNOWN',
    required: false,
    order: 160,
    justification: 'La Ley 21.459 tipifica delitos informáticos relevantes ante accesos no autorizados o exfiltración de datos.',
    legalMatter: 'Delitos informáticos',
    norm: 'Ley N.º 21.459',
    source: 'L21459-001',
    riskLevel: 'alto',
    visibilityCondition: { op: 'nonEmpty', path: 'incidents' },
  },
];
