import type { QuestionSeed } from '../types';

// Preguntas específicas por sector. Se activan cuando el sector fue
// detectado para el diagnóstico (DiagnosisSector) — ver question-engine/engine.ts.
export const SECTORIAL_QUESTIONS: QuestionSeed[] = [
  // --- Salud ---
  {
    code: 'Q-SALUD-001',
    category: 'Sector salud',
    text: '¿Cómo se administra la ficha clínica de los pacientes (soporte físico, electrónico, ambos) y quiénes tienen acceso a ella?',
    answerType: 'LONG_TEXT',
    required: true,
    order: 300,
    justification: 'La ficha clínica tiene un régimen de confidencialidad y acceso específico bajo la Ley 20.584.',
    legalMatter: 'Salud — ficha clínica',
    norm: 'Ley N.º 20.584',
    source: 'L20584-001',
    riskLevel: 'alto',
    requiresDocument: true,
    sectorKeys: ['salud'],
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-SALUD-002',
    category: 'Sector salud',
    text: '¿Se comparte información de pacientes con laboratorios externos, aseguradoras, Isapres o Fonasa? Indique en qué casos.',
    answerType: 'LONG_TEXT',
    required: true,
    order: 310,
    justification: 'El intercambio de datos de salud con terceros requiere resguardos reforzados.',
    legalMatter: 'Salud — comunicación a terceros',
    riskLevel: 'alto',
    sectorKeys: ['salud'],
    visibilityCondition: { op: 'always' },
  },
  // --- Educación ---
  {
    code: 'Q-EDU-001',
    category: 'Sector educación',
    text: '¿Cómo gestiona la información académica y de convivencia escolar de los estudiantes, y quiénes tienen acceso a los informes de convivencia?',
    answerType: 'LONG_TEXT',
    required: true,
    order: 320,
    justification: 'Los informes de convivencia escolar y datos académicos requieren control de acceso reforzado, especialmente al tratarse de menores de edad.',
    legalMatter: 'Educación — datos de menores',
    riskLevel: 'alto',
    sectorKeys: ['educacion'],
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-EDU-002',
    category: 'Sector educación',
    text: '¿Qué información se solicita a los apoderados y cómo se obtiene su autorización para el tratamiento de datos de sus hijos/pupilos?',
    answerType: 'LONG_TEXT',
    required: true,
    order: 330,
    justification: 'El tratamiento de datos de menores de edad exige un análisis específico de la habilitación legal.',
    legalMatter: 'Educación — consentimiento de apoderados',
    riskLevel: 'alto',
    sectorKeys: ['educacion'],
    visibilityCondition: { op: 'always' },
  },
  // --- Comercio electrónico ---
  {
    code: 'Q-ECOM-001',
    category: 'Sector comercio electrónico',
    text: '¿Qué pasarela(s) de pago utiliza y qué datos de la transacción almacena la organización (versus lo que retiene únicamente la pasarela)?',
    answerType: 'LONG_TEXT',
    required: true,
    order: 340,
    justification: 'Distingue el rol de la organización respecto de los datos financieros de la transacción.',
    legalMatter: 'Comercio electrónico — pagos',
    riskLevel: 'medio',
    sectorKeys: ['comercio-electronico'],
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-ECOM-002',
    category: 'Sector comercio electrónico',
    text: '¿Utiliza cookies, píxeles o herramientas de remarketing en el sitio de comercio electrónico? ¿Cuenta con un banner de consentimiento de cookies?',
    answerType: 'YES_NO_UNKNOWN',
    required: true,
    order: 350,
    justification: 'El uso de tecnologías de rastreo en comercio electrónico es un foco típico de riesgo de cumplimiento.',
    legalMatter: 'Comercio electrónico — tracking',
    riskLevel: 'medio',
    sectorKeys: ['comercio-electronico'],
    visibilityCondition: { op: 'always' },
  },
  // --- SaaS / Tecnología ---
  {
    code: 'Q-SAAS-001',
    category: 'Sector SaaS',
    text: 'Cuando su plataforma trata datos personales de los usuarios finales de sus clientes empresariales, ¿actúa como encargado de tratamiento? ¿Existe un contrato de encargo (DPA) con cada cliente?',
    answerType: 'YES_NO_UNKNOWN',
    required: true,
    order: 360,
    justification: 'En modelos SaaS es frecuente que la organización actúe como encargado de tratamiento respecto de datos de terceros.',
    legalMatter: 'SaaS — rol de encargado de tratamiento',
    riskLevel: 'alto',
    requiresDocument: true,
    sectorKeys: ['saas', 'tecnologia'],
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-SAAS-002',
    category: 'Sector SaaS',
    text: '¿En qué país(es) se alojan los datos de la plataforma (proveedor de infraestructura cloud) y existen sub-encargados adicionales?',
    answerType: 'LONG_TEXT',
    required: true,
    order: 370,
    justification: 'El alojamiento en la nube fuera de Chile puede constituir una transferencia internacional.',
    legalMatter: 'SaaS — infraestructura y transferencias',
    riskLevel: 'alto',
    sectorKeys: ['saas', 'tecnologia'],
    visibilityCondition: { op: 'always' },
  },
  // --- Laboral / RR.HH. ---
  {
    code: 'Q-LAB-001',
    category: 'Sector laboral',
    text: '¿Cómo se utilizan las licencias médicas de los trabajadores dentro de la organización? ¿Se limita su circulación a quienes estrictamente lo requieren?',
    answerType: 'LONG_TEXT',
    required: true,
    order: 380,
    justification: 'Las licencias médicas contienen datos de salud y su uso indebido en decisiones laborales es un riesgo frecuente.',
    legalMatter: 'Laboral — licencias médicas',
    riskLevel: 'alto',
    sectorKeys: ['laboral'],
    visibilityCondition: { op: 'always' },
  },
  {
    code: 'Q-LAB-002',
    category: 'Sector laboral',
    text: '¿Existe videovigilancia o monitoreo de correo/actividad de los trabajadores? ¿Se informó dicha política al personal?',
    answerType: 'YES_NO_UNKNOWN',
    required: true,
    order: 390,
    justification: 'El control laboral mediante videovigilancia o monitoreo debe ser informado y proporcional.',
    legalMatter: 'Laboral — control y videovigilancia',
    riskLevel: 'medio',
    sectorKeys: ['laboral'],
    visibilityCondition: { op: 'always' },
  },
  // --- Financiero ---
  {
    code: 'Q-FIN-001',
    category: 'Sector financiero',
    text: '¿La organización realiza evaluación de riesgo crediticio (scoring)? ¿El proceso es automatizado y existe revisión humana ante resultados adversos?',
    answerType: 'YES_NO_UNKNOWN',
    required: true,
    order: 400,
    justification: 'El scoring automatizado sin intervención humana es un foco de riesgo relevante y potencial materia del nuevo régimen.',
    legalMatter: 'Financiero — decisiones automatizadas',
    riskLevel: 'alto',
    sectorKeys: ['financiero'],
    visibilityCondition: { op: 'always' },
  },
];
