export interface SectorSeed {
  key: string;
  name: string;
  description: string;
  activationIndicators: string[];
  commonProcessing: string[];
  commonSubjects: string[];
  dataCategories: string[];
  sensitiveData: string[];
  commonProviders: string[];
  commonRisks: string[];
  officialLinks: string[];
}

export const SECTORS: SectorSeed[] = [
  {
    key: 'salud',
    name: 'Salud',
    description: 'Prestadores de salud, clínicas, centros médicos, laboratorios y profesionales de la salud.',
    activationIndicators: ['ficha clínica', 'paciente', 'consulta médica', 'examen', 'receta', 'historial médico'],
    commonProcessing: ['atención de pacientes', 'agendamiento de horas', 'facturación de prestaciones', 'telemedicina'],
    commonSubjects: ['pacientes', 'trabajadores', 'profesionales de salud'],
    dataCategories: ['identificación', 'contacto', 'previsión de salud', 'diagnósticos', 'tratamientos'],
    sensitiveData: ['datos de salud', 'ficha clínica'],
    commonProviders: ['sistemas de ficha clínica electrónica', 'laboratorios externos', 'aseguradoras', 'Isapres/Fonasa'],
    commonRisks: ['exposición de datos de salud', 'acceso indebido a ficha clínica', 'conservación indefinida de historiales'],
    officialLinks: ['https://www.superdesalud.gob.cl/', 'https://www.minsal.cl/'],
  },
  {
    key: 'educacion',
    name: 'Educación',
    description: 'Colegios, universidades, institutos y centros de formación.',
    activationIndicators: ['alumno', 'matrícula', 'apoderado', 'notas', 'libro de clases'],
    commonProcessing: ['matrícula', 'evaluación académica', 'convivencia escolar', 'comunicación con apoderados'],
    commonSubjects: ['estudiantes', 'apoderados', 'docentes', 'personal administrativo'],
    dataCategories: ['identificación', 'rendimiento académico', 'asistencia', 'datos socioeconómicos'],
    sensitiveData: ['situación de salud/discapacidad', 'informes psicosociales'],
    commonProviders: ['plataformas de gestión escolar', 'plataformas de e-learning'],
    commonRisks: ['exposición de notas o informes de convivencia', 'uso de datos de menores de edad'],
    officialLinks: ['https://www.supereduc.cl/'],
  },
  {
    key: 'laboral',
    name: 'Laboral / Recursos Humanos',
    description: 'Gestión de trabajadores dependientes en cualquier organización.',
    activationIndicators: ['contrato de trabajo', 'remuneraciones', 'liquidación de sueldo', 'trabajador'],
    commonProcessing: ['reclutamiento', 'nómina', 'evaluación de desempeño', 'control de asistencia'],
    commonSubjects: ['trabajadores', 'postulantes'],
    dataCategories: ['identificación', 'datos bancarios', 'datos previsionales', 'evaluaciones de desempeño'],
    sensitiveData: ['licencias médicas', 'afiliación sindical'],
    commonProviders: ['software de nómina', 'AFP', 'mutualidades'],
    commonRisks: ['uso de licencias médicas para decisiones laborales', 'videovigilancia de trabajadores'],
    officialLinks: ['https://www.dt.gob.cl/'],
  },
  {
    key: 'financiero',
    name: 'Financiero',
    description: 'Bancos, cooperativas, emisores de tarjetas, fintech y otorgantes de crédito.',
    activationIndicators: ['crédito', 'cuenta corriente', 'tarjeta', 'evaluación crediticia'],
    commonProcessing: ['evaluación de riesgo crediticio', 'prevención de fraude', 'cobranza'],
    commonSubjects: ['clientes', 'deudores', 'garantes'],
    dataCategories: ['datos financieros', 'historial crediticio', 'identificación'],
    sensitiveData: ['situación socioeconómica sensible'],
    commonProviders: ['burós de crédito', 'procesadores de pago'],
    commonRisks: ['scoring automatizado sin explicación', 'transferencias a burós de crédito'],
    officialLinks: ['https://www.cmfchile.cl/'],
  },
  {
    key: 'seguros',
    name: 'Seguros',
    description: 'Compañías de seguros, corredores y liquidadores.',
    activationIndicators: ['póliza', 'siniestro', 'prima', 'asegurado'],
    commonProcessing: ['suscripción de pólizas', 'liquidación de siniestros'],
    commonSubjects: ['asegurados', 'beneficiarios'],
    dataCategories: ['identificación', 'datos de salud (seguros de vida/salud)', 'datos patrimoniales'],
    sensitiveData: ['datos de salud'],
    commonProviders: ['reaseguradoras', 'liquidadores externos'],
    commonRisks: ['transferencia de datos de salud a reaseguradoras extranjeras'],
    officialLinks: ['https://www.cmfchile.cl/'],
  },
  {
    key: 'comercio',
    name: 'Comercio',
    description: 'Comercio minorista y mayorista en general.',
    activationIndicators: ['venta', 'cliente', 'punto de venta', 'boleta'],
    commonProcessing: ['ventas', 'programas de fidelización', 'marketing directo'],
    commonSubjects: ['clientes'],
    dataCategories: ['identificación', 'historial de compras', 'preferencias'],
    sensitiveData: [],
    commonProviders: ['plataformas de punto de venta', 'CRM'],
    commonRisks: ['uso de datos para perfilamiento comercial sin base legal'],
    officialLinks: ['https://www.sernac.cl/'],
  },
  {
    key: 'inmobiliario',
    name: 'Inmobiliario',
    description: 'Inmobiliarias, corretaje y administración de propiedades.',
    activationIndicators: ['arriendo', 'venta de propiedad', 'corretaje', 'promesa de compraventa'],
    commonProcessing: ['evaluación de arrendatarios', 'gestión contractual'],
    commonSubjects: ['clientes', 'arrendatarios', 'propietarios'],
    dataCategories: ['identificación', 'datos financieros', 'datos laborales'],
    sensitiveData: [],
    commonProviders: ['plataformas de verificación de antecedentes comerciales'],
    commonRisks: ['consulta de antecedentes comerciales sin autorización adecuada'],
    officialLinks: [],
  },
  {
    key: 'condominios',
    name: 'Condominios',
    description: 'Administración de condominios y comunidades.',
    activationIndicators: ['copropietario', 'gasto común', 'administración de condominio'],
    commonProcessing: ['cobranza de gastos comunes', 'control de acceso'],
    commonSubjects: ['copropietarios', 'arrendatarios', 'visitas'],
    dataCategories: ['identificación', 'datos de contacto', 'registros de acceso'],
    sensitiveData: [],
    commonProviders: ['sistemas de control de acceso', 'cámaras de seguridad'],
    commonRisks: ['videovigilancia sin política clara', 'exposición de datos en libros de acceso'],
    officialLinks: [],
  },
  {
    key: 'marketing',
    name: 'Marketing y publicidad',
    description: 'Agencias de marketing, publicidad digital y medición.',
    activationIndicators: ['campaña publicitaria', 'base de datos de contactos', 'email marketing'],
    commonProcessing: ['envío de campañas', 'segmentación de audiencias', 'publicidad programática'],
    commonSubjects: ['prospectos', 'clientes de terceros'],
    dataCategories: ['identificación', 'comportamiento en línea', 'preferencias'],
    sensitiveData: [],
    commonProviders: ['plataformas de email marketing', 'redes publicitarias', 'herramientas de analítica'],
    commonRisks: ['tracking sin consentimiento', 'compra de bases de datos de terceros'],
    officialLinks: [],
  },
  {
    key: 'tecnologia',
    name: 'Tecnología',
    description: 'Empresas de desarrollo de software y tecnología en general.',
    activationIndicators: ['plataforma tecnológica', 'aplicación', 'desarrollo de software'],
    commonProcessing: ['desarrollo de producto', 'soporte técnico', 'analítica de uso'],
    commonSubjects: ['usuarios finales', 'clientes B2B'],
    dataCategories: ['identificación', 'datos de uso', 'logs técnicos'],
    sensitiveData: [],
    commonProviders: ['proveedores de nube', 'herramientas de monitoreo'],
    commonRisks: ['almacenamiento en la nube fuera de Chile', 'logs con datos personales sin anonimizar'],
    officialLinks: [],
  },
  {
    key: 'saas',
    name: 'SaaS',
    description: 'Software como servicio para empresas o consumidores.',
    activationIndicators: ['suscripción', 'plan mensual', 'multi-tenant', 'usuarios de la plataforma', 'plataforma saas', 'clientes empresariales', 'usuarios finales'],
    commonProcessing: ['gestión de cuentas de usuario', 'facturación recurrente', 'soporte'],
    commonSubjects: ['usuarios de clientes (encargo de tratamiento)'],
    dataCategories: ['identificación', 'datos de uso del producto'],
    sensitiveData: [],
    commonProviders: ['proveedores de infraestructura cloud', 'pasarelas de pago'],
    commonRisks: ['rol de encargado de tratamiento no formalizado contractualmente'],
    officialLinks: [],
  },
  {
    key: 'ong',
    name: 'Organizaciones sin fines de lucro',
    description: 'Fundaciones, corporaciones y ONG.',
    activationIndicators: ['donante', 'voluntario', 'beneficiario del programa social'],
    commonProcessing: ['gestión de donantes', 'programas sociales', 'voluntariado'],
    commonSubjects: ['donantes', 'beneficiarios', 'voluntarios'],
    dataCategories: ['identificación', 'datos socioeconómicos'],
    sensitiveData: ['situación de vulnerabilidad social'],
    commonProviders: ['plataformas de donación en línea'],
    commonRisks: ['exposición de datos de beneficiarios vulnerables'],
    officialLinks: [],
  },
  {
    key: 'profesionales-independientes',
    name: 'Profesionales independientes',
    description: 'Abogados, contadores, consultores y otros profesionales que operan de forma independiente.',
    activationIndicators: ['cliente particular', 'honorarios', 'asesoría profesional'],
    commonProcessing: ['prestación de servicios profesionales', 'facturación'],
    commonSubjects: ['clientes'],
    dataCategories: ['identificación', 'datos del caso o asunto'],
    sensitiveData: ['datos que surjan del secreto profesional (ej. de salud o judiciales)'],
    commonProviders: ['software de gestión de casos'],
    commonRisks: ['manejo de información amparada por secreto profesional en canales inseguros'],
    officialLinks: [],
  },
  {
    key: 'transporte',
    name: 'Transporte',
    description: 'Transporte de pasajeros y carga.',
    activationIndicators: ['pasajero', 'flota', 'conductor', 'ruta'],
    commonProcessing: ['gestión de viajes', 'geolocalización de vehículos'],
    commonSubjects: ['pasajeros', 'conductores'],
    dataCategories: ['identificación', 'geolocalización'],
    sensitiveData: [],
    commonProviders: ['plataformas de geolocalización/GPS'],
    commonRisks: ['geolocalización continua de conductores y pasajeros'],
    officialLinks: [],
  },
  {
    key: 'turismo',
    name: 'Turismo',
    description: 'Agencias de viaje y operadores turísticos.',
    activationIndicators: ['reserva de viaje', 'paquete turístico', 'pasajero'],
    commonProcessing: ['gestión de reservas', 'coordinación con proveedores turísticos'],
    commonSubjects: ['clientes/turistas'],
    dataCategories: ['identificación', 'datos de pasaporte', 'preferencias de viaje'],
    sensitiveData: [],
    commonProviders: ['aerolíneas', 'hoteles', 'plataformas de reserva'],
    commonRisks: ['transferencia de datos de pasaporte a proveedores extranjeros'],
    officialLinks: [],
  },
  {
    key: 'hoteleria',
    name: 'Hotelería',
    description: 'Hoteles, hostales y alojamiento turístico.',
    activationIndicators: ['huésped', 'reserva de habitación', 'check-in'],
    commonProcessing: ['registro de huéspedes', 'facturación', 'fidelización'],
    commonSubjects: ['huéspedes'],
    dataCategories: ['identificación', 'datos de documento de viaje'],
    sensitiveData: [],
    commonProviders: ['plataformas de reserva (OTA)', 'sistemas de gestión hotelera (PMS)'],
    commonRisks: ['registro obligatorio de huéspedes con retención prolongada'],
    officialLinks: [],
  },
  {
    key: 'telecomunicaciones',
    name: 'Telecomunicaciones',
    description: 'Proveedores de servicios de telecomunicaciones e Internet.',
    activationIndicators: ['abonado', 'plan telefónico', 'tráfico de datos'],
    commonProcessing: ['provisión de servicio', 'facturación', 'atención al cliente'],
    commonSubjects: ['abonados'],
    dataCategories: ['identificación', 'datos de tráfico y ubicación'],
    sensitiveData: [],
    commonProviders: ['proveedores de red', 'call centers'],
    commonRisks: ['acceso a datos de tráfico y ubicación sin control adecuado'],
    officialLinks: [],
  },
  {
    key: 'medios',
    name: 'Medios de comunicación',
    description: 'Medios de prensa, radio, TV y plataformas de contenido.',
    activationIndicators: ['suscriptor', 'audiencia', 'comentarios de usuarios'],
    commonProcessing: ['gestión de suscripciones', 'moderación de comentarios'],
    commonSubjects: ['suscriptores', 'audiencia'],
    dataCategories: ['identificación', 'datos de comportamiento de lectura'],
    sensitiveData: [],
    commonProviders: ['plataformas de analítica de audiencia'],
    commonRisks: ['tratamiento periodístico de datos personales sensibles'],
    officialLinks: [],
  },
  {
    key: 'servicios-publicos',
    name: 'Servicios públicos / utilities',
    description: 'Agua, electricidad, gas y otros servicios básicos.',
    activationIndicators: ['medidor', 'cuenta de servicio', 'cliente regulado'],
    commonProcessing: ['facturación', 'lectura de consumo'],
    commonSubjects: ['clientes/usuarios del servicio'],
    dataCategories: ['identificación', 'datos de consumo'],
    sensitiveData: [],
    commonProviders: ['empresas de medición y facturación'],
    commonRisks: ['perfiles de consumo detallados (smart metering)'],
    officialLinks: [],
  },
  {
    key: 'asociaciones',
    name: 'Asociaciones gremiales / sindicatos',
    description: 'Asociaciones gremiales, colegios profesionales y sindicatos.',
    activationIndicators: ['socio', 'afiliado', 'cuota social'],
    commonProcessing: ['gestión de membresía', 'comunicaciones a socios'],
    commonSubjects: ['socios/afiliados'],
    dataCategories: ['identificación', 'datos laborales'],
    sensitiveData: ['afiliación sindical o gremial'],
    commonProviders: [],
    commonRisks: ['exposición de la afiliación sindical/gremial de una persona'],
    officialLinks: [],
  },
  {
    key: 'comercio-electronico',
    name: 'Comercio electrónico',
    description: 'Tiendas en línea y marketplaces.',
    activationIndicators: ['carro de compra', 'checkout', 'pasarela de pago', 'tienda online'],
    commonProcessing: ['gestión de pedidos', 'pagos en línea', 'logística de despacho'],
    commonSubjects: ['clientes'],
    dataCategories: ['identificación', 'dirección de despacho', 'historial de compras'],
    sensitiveData: [],
    commonProviders: ['pasarelas de pago', 'couriers', 'plataformas de e-commerce'],
    commonRisks: ['retención de datos de tarjetas fuera de norma PCI-DSS (materia distinta a datos personales pero relacionada)'],
    officialLinks: ['https://www.sernac.cl/'],
  },
];
