-- CreateEnum
CREATE TYPE "ExportKind" AS ENUM ('DIAGNOSTICO_COMPLETO', 'CUESTIONARIO_PERSONALIZADO');

-- AlterTable
ALTER TABLE "Export" ADD COLUMN     "kind" "ExportKind" NOT NULL DEFAULT 'DIAGNOSTICO_COMPLETO';
